### PR TITLE
v0.2.0

### PR DESCRIPTION
**Pull request by doug-martin**
* Added etcd support [#12](https://github.com/C2FO/gofigure/pull/12) - [@brockwood](https://github.com/brockwood)

@brockwood had to update some files for jshint, and updated some other dev dependencies please review.

- [x] @brockwood

### CODE REVIEW

**Comment by brockwood** [comment]
Looks good.

**Comment by doug-martin** [comment]
Did you see my comment on the other PR about the `'type'`?

**Comment by doug-martin** [comment]
This line https://github.com/doug-martin/gofigure/blob/master/lib/index.js#L110

**Comment by brockwood** [comment]
Sorry, I missed your comment in the other PR. 'type' is covered here: 

https://github.com/C2FO/gofigure#type

It allows a user to do per type overrides and is set on the environment with NODE_TYPE. This allows us in Etcd to do the overrides for things like calculator and adjuster.

**Pull request merged**
